### ISSUE TITLE
Additional nav link section formatting

### ISSUE THREAD

**Issue by benkmoore** [tbakerx/react-resume-template#36]
Hey Tim, awesome website template thanks a mill! Trying to add additional sections and I can't figure out how to add them correctly so that they get the color change when selected/deselected. I know the function handler in init.js adds/removes the style class `current` to the section id but I can't figure out why it won't recognize the new section as a section or where all the sections are defined for the project. You can see exactly what I've tried [here](https://github.com/benkmoore/mypage). Any help would be great thanks!

**Comment by tbakerx** [comment]
Hey @benkmoore so sorry for the inactivity and thanks for using the project! I'm unsure if you're still using it but I just released a completely re-worked/written v2 that would address this issue directly. I'm deprecating v1 and will be closing all open issues at this time.

If you intend to continue using v1 feel free to reach out and I can try to give you a hand resolving that, but otherwise I'd recommend giving the new version a try. Cheers, and thanks again for giving it a try!
