### ISSUE TITLE
How do I make the contact form work?

### ISSUE THREAD

**Issue by akshzyx** [tbakerx/react-resume-template#88]
Even after filling the contact form the SUBMIT button just doesn't work. How do I solve this?

**Comment by tbakerx** [comment]
I've got a note in the README about this: https://github.com/tbakerx/react-resume-template#5-hook-up-contact-form
Due to the wide array of options in implementation for this (Next api routes, your own server, etc.) and potential email providers to send with, I've opted to leave the implementation up to the user.

You'll have to implement the form submission and email sending in a way that meets your own needs. Feel free to reach out to me if you need, and I can point you in the right direction.

**Comment by akshzyx** [comment]
So I am using BREVO([Sendinblue](https://www.brevo.com/)), how do I set it up? Can you help a little.
